# Análisis de datos con `pandas`: ejercicios

**NOTAS**
 - Hay muchas formas de resolver cada problema, encuentra la tuya.
 - Crea las celdas extra que necesites.
 - Recuerda que una celda puede ser de tipo Código, o de tipo Markdown. Utiliza las segundas para escribir texto y explicaciones si lo precisas.
 - Intenta crear variables a la hora de resolver los ejercicios.
 - Puedes apoyarte en internet: todos los programadores lo hacemos a diario.

<img width=500 src="https://upload.wikimedia.org/wikipedia/commons/3/31/TitanicBeken.jpg">

Importamos el csv del titanic a un dataframe

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("./datasets/titanic.csv")

Cada fila representa a un pasajero

Echa un vistazo a las primeras filas del dataframe. Y a las últimas. Y a una muestra aleatoria

Cuántos pasajeros hay en este dataframe?

In [6]:
df.shape

(1309, 11)

In [4]:
df.head()

,Name,Sex,Age,Pclass,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,"Karaic, Mr. Milan",male,30.0,3,0,0,349246,7.8958,NaN,S,0
1,"Dean, Mrs. Bertram",female,33.0,3,1,2,C.A. 2315,20.5750,NaN,S,1
2,"Rice, Mrs. William",female,39.0,3,0,5,382652,29.1250,NaN,Q,0
3,"Davidson, Mrs. Thornton",female,27.0,1,1,2,F.C. 12750,52.0000,B71,S,1
4,"Ridsdale, Miss. Lucy",female,50.0,2,0,0,W./C. 14258,10.5000,NaN,S,1

In [5]:
df.tail()

,Name,Sex,Age,Pclass,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
1304,"Strilic, Mr. Ivan",male,27.0,3,0,0,315083,8.6625,NaN,S,0
1305,"Bengtsson, Mr. John Viktor",male,26.0,3,0,0,347068,7.7750,NaN,S,0
1306,"Gustafsson, Mr. Karl Gideon",male,19.0,3,0,0,347069,7.7750,NaN,S,0
1307,"Gustafsson, Mr. Anders Vilhelm",male,37.0,3,2,0,3101276,7.9250,NaN,S,0
1308,"McDermott, Miss. Brigdet Delia",female,NaN,3,0,0,330932,7.7875,NaN,Q,1

In [16]:
df.sample(5)

,Name,Sex,Age,Pclass,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
1274,"Loring, Mr. Joseph Holland",male,30.0,1,0,0,113801,45.5000,NaN,S,0
1204,"Penasco y Castellana, Mr. Victor de Satode",male,18.0,1,1,0,PC 17758,108.9000,C65,C,0
454,"Collyer, Mr. Harvey",male,31.0,2,1,1,C.A. 31921,26.2500,NaN,S,0
1143,"Matinoff, Mr. Nicola",male,NaN,3,0,0,349255,7.8958,NaN,C,0
435,"Williams, Mr. Leslie",male,28.5,3,0,0,54636,16.1000,NaN,S,0

Cuáles son las columnas del dataframe?

In [19]:
df.columns

Index(['Name', 'Sex', 'Age', 'Pclass', 'SibSp', 'Parch', 'Ticket', 'Fare',
       'Cabin', 'Embarked', 'Survived'],
      dtype='object')

Cuál es la edad media de los pasajeros? Y la mediana? Cómo interpretas el resultado?

In [26]:
df.Age.mean().round(1)

np.float64(29.9)

In [27]:
df.Age.median()

np.float64(28.0)

Cuánto costó el billete más caro?

In [29]:
df.Fare.max()

np.float64(512.3292)

Cuánto pagaron entre todos los pasajeros?

In [32]:
df.Fare.sum().round(0)

np.float64(43550.0)

In [ ]:
21.7
0.0343
345000
22700

Filtra el dataframe para ver sólo a las mujeres

In [46]:
df_women = df[df.Sex == 'female']

In [47]:
df_women.head()

,Name,Sex,Age,Pclass,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
1,"Dean, Mrs. Bertram",female,33.0,3,1,2,C.A. 2315,20.5750,NaN,S,1
2,"Rice, Mrs. William",female,39.0,3,0,5,382652,29.1250,NaN,Q,0
3,"Davidson, Mrs. Thornton",female,27.0,1,1,2,F.C. 12750,52.0000,B71,S,1
4,"Ridsdale, Miss. Lucy",female,50.0,2,0,0,W./C. 14258,10.5000,NaN,S,1
5,"Douglas, Mrs. Frederick Charles",female,27.0,1,1,1,PC 17558,247.5208,B58 B60,C,1

Filtra el dataframe para ver sólo a los niños (menores de 15 años)

In [50]:
df[df.Age < 15]

,Name,Sex,Age,Pclass,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
9,"Watt, Miss. Bertha J",female,12.00,2,0,0,C.A. 33595,15.7500,NaN,S,1
10,"Skoog, Miss. Mabel",female,9.00,3,3,2,347088,27.9000,NaN,S,0
35,"Sweet, Mr. George Frederick",male,14.00,2,0,0,220845,65.0000,NaN,S,0
44,"Ryerson, Master. John Borie",male,13.00,1,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,1
72,"Coutts, Master. William Loch ""William""",male,3.00,3,1,1,C.A. 37671,15.9000,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1243,"Nasser, Mrs. Nicholas",female,14.00,2,1,0,237736,30.0708,NaN,C,1
1261,"Johnson, Master. Harold Theodor",male,4.00,3,1,1,347742,11.1333,NaN,S,1
1291,"Richards, Master. George Sibley",male,0.83,2,1,1,29106,18.7500,NaN,S,1
1301,"Asplund, Master. Filip Oscar",male,13.00,3,4,2,347077,31.3875,NaN,S,0
1303,"Aks, Master. Philip Frank",male,0.83,3,0,1,392091,9.3500,NaN,S,1

Filtra el dataframe para ver sólo a mujeres y niños

In [53]:
df[(df.Sex == "female") | (df.Age < 15)]

,Name,Sex,Age,Pclass,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
1,"Dean, Mrs. Bertram",female,33.00,3,1,2,C.A. 2315,20.5750,NaN,S,1
2,"Rice, Mrs. William",female,39.00,3,0,5,382652,29.1250,NaN,Q,0
3,"Davidson, Mrs. Thornton",female,27.00,1,1,2,F.C. 12750,52.0000,B71,S,1
4,"Ridsdale, Miss. Lucy",female,50.00,2,0,0,W./C. 14258,10.5000,NaN,S,1
5,"Douglas, Mrs. Frederick Charles",female,27.00,1,1,1,PC 17558,247.5208,B58 B60,C,1
...,...,...,...,...,...,...,...,...,...,...,...
1300,"Connolly, Miss. Kate",female,30.00,3,0,0,330972,7.6292,NaN,Q,0
1301,"Asplund, Master. Filip Oscar",male,13.00,3,4,2,347077,31.3875,NaN,S,0
1302,"Cassebeer, Mrs. Henry Arthur Jr",female,NaN,1,0,0,17770,27.7208,NaN,C,1
1303,"Aks, Master. Philip Frank",male,0.83,3,0,1,392091,9.3500,NaN,S,1
1308,"McDermott, Miss. Brigdet Delia",female,NaN,3,0,0,330932,7.7875,NaN,Q,1

Quién era el pasajero más joven y qué edad tenía?

In [54]:
df.Age.min()

np.float64(0.17)

In [56]:
df[df.Age == df.Age.min()]

,Name,Sex,Age,Pclass,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
151,"Dean, Miss. Elizabeth Gladys Millvina",female,0.17,3,1,2,C.A. 2315,20.575,NaN,S,1

Cuántos pasajeros eran menores de 20? Qué porcentaje?

In [59]:
n_big = (df.Age < 20).sum()

In [60]:
n_big

np.int64(225)

In [61]:
df.shape

(1309, 11)

In [62]:
round(n_big / df.shape[0] * 100, 1)

np.float64(17.2)

Cual es el decil 8 de la edad?

In [63]:
df.Age.quantile(0.80)

np.float64(42.0)

In [64]:
df.Age.quantile(0.90)

np.float64(50.0)

In [65]:
df.Age.quantile(0.10)

np.float64(14.0)

In [68]:
import numpy as np

In [71]:
df.Age.quantile(list(np.arange(0, 1.1, 0.1)))

0.0     0.17
0.1    14.00
0.2    19.00
0.3    22.00
0.4    25.00
0.5    28.00
0.6    31.00
0.7    36.00
0.8    42.00
0.9    50.00
1.0    80.00
Name: Age, dtype: float64

Cuánta gente sobrevivió? Cuánta murió?

In [73]:
df.Survived.sum()

np.int64(500)

In [74]:
df.shape[0] - df.Survived.sum()

np.int64(809)

Cuánta gente viajaba en cada clase?

In [75]:
df.head()

,Name,Sex,Age,Pclass,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,"Karaic, Mr. Milan",male,30.0,3,0,0,349246,7.8958,NaN,S,0
1,"Dean, Mrs. Bertram",female,33.0,3,1,2,C.A. 2315,20.5750,NaN,S,1
2,"Rice, Mrs. William",female,39.0,3,0,5,382652,29.1250,NaN,Q,0
3,"Davidson, Mrs. Thornton",female,27.0,1,1,2,F.C. 12750,52.0000,B71,S,1
4,"Ridsdale, Miss. Lucy",female,50.0,2,0,0,W./C. 14258,10.5000,NaN,S,1

In [78]:
df.Sex.value_counts()

Sex
male      843
female    466
Name: count, dtype: int64

In [79]:
df.Embarked.value_counts()

Embarked
S    914
C    270
Q    123
Name: count, dtype: int64

In [77]:
df.Pclass.value_counts().sort_index()

Pclass
1    323
2    277
3    709
Name: count, dtype: int64

Era más probable sobrevivir siendo de primera clase?

In [80]:
pd.crosstab(df.Pclass, df.Survived)

Survived    0    1
Pclass
1         123  200
2         158  119
3         528  181

In [83]:
pd.crosstab(df.Pclass, df.Survived, normalize="index").round(2)

Survived     0     1
Pclass
1         0.38  0.62
2         0.57  0.43
3         0.74  0.26

In [84]:
pd.crosstab(df.Pclass, df.Survived, normalize="columns").round(2)

Survived     0     1
Pclass
1         0.15  0.40
2         0.20  0.24
3         0.65  0.36

Era más probable sobrevivir siendo mujer?

Con cuántos familiares viajaba la gente? (informado en la columna SibSp)

Cuántas puertas de embarque había?

Crea un dataframe con las personas que viajaban en primera clase

Crea un dataframe que contenga mujeres y niños

Crea un dataframe con la gente que no viajara en la `S`

Crea un dataframe con todas las "Miss"

Crea una columna booleana que almacene si el pasajero es mayor de edad

Crea una columna con el año de nacimiento del pasajero

Afectó el número de familiares a la probabilidad de sobrevivir?

Eran más caros los billetes de primera clase?

Eran más jovenes los hombres que las mujeres del titanic?

Crea una columna que almacene si el número de ticket del pasajero contiene alguna letra. Define para ello una función y usa `apply`

Exporta los datos a un csv llamado `titanic_enriched.csv`